### ISSUE TITLE
Question: Is data cached / saved or transient with the API call?

### ISSUE THREAD

**Issue by simpsus** [gregmorse/numerai_era_data#12]
Apart from the speed of the (training) pipeline it owuld mean additional complexity on the client side if each API call queries the online sources.

No feature request, I just want to know what I am getting myself into.

Thx for your effort!

**Comment by gregmorse** [comment]
Yes, data is cached.  

The cache is only updated if one of the following occurs: 
- a new era starts (for get_all_eras()) 
- a new day begins (for get_current_daily())
- a new column is added to any of the data sources
- a new data source is added
